ui

diff --git a/web/ui/.github/workflows/deploy.yml b/web/ui/.github/workflows/deploy.yml
--- a/web/ui/.github/workflows/deploy.yml
+++ b/web/ui/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Blog deploy
+name: Main deploy
 on:
   push:
     branches:
@@ -10,28 +10,44 @@ jobs:
     
     steps:
     - name: Checkout
-      uses: actions/checkout@v2   
+      uses: actions/checkout@v2
 
     - name: Update the repo from web server
-      uses: appleboy/ssh-action@v0.1.4      
+      uses: appleboy/ssh-action@v0.1.7
       env:
         NODE_OPTIONS: --openssl-legacy-provider
         CI: false
+        ANALYZE: true
       with:
-        host: ${{ secrets.WEB_SERVER }}
+        host: ${{ secrets.WEB_SERVER_2 }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.PRIV_KEY }}
         envs: CI, NODE_OPTIONS
         script: |
-          cd ~/blog.notional.ventures
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/github@web-server-2
+          cd ~/CNWeb-30
+          export PATH=/root/.nvm/versions/node/v19.1.0/bin/:$PATH
           git stash save --keep-index --include-untracked
           git pull
-          export PATH=/root/.nvm/versions/node/v18.9.0/bin/:$PATH
 
           if ! [ $? -eq 0 ]; then
               echo "git pull failed with errors."
               exit 1
           fi
 
+          cp cn-web.service /etc/systemd/system/cn-web.service
+          systemctl stop cn-web.service
+          systemctl daemon-reload
+          echo "Service file copied!"
+
           npm install
           npm run build
+
+          if [ $? -eq 0 ]; then
+              systemctl restart cn-web.service
+              systemctl is-active --quiet cn-web.service && echo "Web server restarted successfully." || (echo "Web server failed to restart." && exit 1)
+          else
+              echo "npm run build failed with error. Stopped restarting the web server."
+              exit 1
+          fi
